apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'com.monkeycode.screenrecorder'
    compileSdk 34

    defaultConfig {
        applicationId "com.monkeycode.screenrecorder"
        minSdk 24
        targetSdk 34
        versionCode 57
        versionName "5.0451"
    }

    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword "android"
            keyAlias "screenrecorder"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
}
